<?php
defined('_JEXEC') or die;
$doc = JFactory::getDocument();
class ProductionViewGlobal extends JViewLegacy{

	public function display($tpl = NULL)
	{
		parent::display($tpl); // TODO: Change the autogenerated stub
	}
}