<?php
defined('_JEXEC') or die;

class ProductionViewGlobal extends JViewLegacy{

	public function display($tpl = NULL)
	{
		$workshop = $this->get('Workshop');
		$this->workshop = $workshop;
		parent::display($tpl); // TODO: Change the autogenerated stub
	}
}